[package]
name = "cargo-changeset"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "A cargo subcommand for managing changesets"

[[bin]]
name = "cargo-changeset"
path = "src/main.rs"

[dependencies]
changeset-core = { workspace = true }
changeset-parse = { workspace = true }
changeset-git = { workspace = true }
changeset-version = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
